<?php

namespace Tests\Feature;

use App\Models\Post;
use App\Services\ArticleImageService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Mockery;
use Tests\TestCase;

class PostObserverAutoGeneratedCoverTest extends TestCase
{
    use RefreshDatabase;

    public function test_publishing_auto_generated_post_triggers_cover_attachment(): void
    {
        Queue::fake();

        $mock = Mockery::mock(ArticleImageService::class);
        $mock->shouldReceive('attachCoverImage')->once()->andReturn(true);
        $this->app->instance(ArticleImageService::class, $mock);

        $post = Post::create([
            'title' => 'Judul Uji Auto',
            'slug' => 'judul-uji-auto',
            'excerpt' => null,
            'body' => 'Isi uji',
            'status' => 'draft',
            'published_at' => null,
            'author_id' => null,
            'source_type' => 'auto_generated',
            'article_topic_id' => null,
            'generation_log_id' => null,
            'ai_disclosure' => false,
        ]);

        $post->update([
            'status' => 'published',
            'published_at' => now(),
        ]);
    }
}

